services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: newsaggregator-app
    container_name: newsaggregatorapi_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - newsaggregator_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=newsaggregator
      - DB_USERNAME=newsaggregator
      - DB_PASSWORD=Nigeria@123
      - NEWS_API_KEY=34339a5626bf4cd1afdf956f955fadab
      - GUARDIAN_API_KEY=2b56f23d-bd72-4d99-9bb3-04161a68a618
      - NYT_API_KEY=VFY4NkaQzi6GOgBCWR4UAraUg3h87NlX
      - L5_SWAGGER_GENERATE_ALWAYS=true
      - L5_SWAGGER_OPEN_API_SPEC_VERSION='3.0.0'
      - SWAGGER_BASE_URL=http://127.0.0.1:8000/api
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: newsaggregatorapi_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password@123
      MYSQL_DATABASE: newsaggregator
      MYSQL_USER: newsaggregator
      MYSQL_PASSWORD: Nigeria@123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - newsaggregator_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Composer container to manage dependencies
  composer:
    image: composer:2.7
    container_name: composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - newsaggregator_network
    command: [ "composer", "install" ]

networks:
  newsaggregator_network:


volumes:
  db_data:
